<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
    $_items = $block->getReviewsCollection()->getItems();
    $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)):?>
<div class="block review-list" id="customer-reviews">
    <span class="reviews-count"><?php echo __('Reviews count') . ' (' . count($_items) . ')' ?></span>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
        <?php foreach ($_items as $_review):?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
<!--                <div class="review-title" itemprop="name">--><?php //echo $block->escapeHtml($_review->getTitle()) ?><!--</div>-->
                <?php if (count($_review->getRatingVotes())): ?>
                <div class="review-ratings">
                    <h3><?php echo __('Rating Value'); ?></h3>
                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
<!--                        <span class="label rating-label"><span>--><?php //echo $block->escapeHtml($_vote->getRatingCode()) ?><!--</span></span>-->
                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
	                        <meta itemprop="worstRating" content = "1"/>
	                        <meta itemprop="bestRating" content = "100"/>
                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                            </span>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    <strong class="rating-value"><?php /* @escapeNotVerified */ echo number_format($_vote->getValue(), 1); ?></strong>
                </div>
                <?php endif; ?>
                <div class="review-content" itemprop="description">
                    <div class="review-details">
                        <h3><strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong></h3>
                        <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>">
                            <?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>
                        </time>
                    </div>
                    <div class="review-text">
                        <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                    </div>
                    <div class="advant-and-disadvant">
                        <div>
                            <span class="advantages"><?php echo __('Advantages'); ?>:</span>
                            <?php echo __('хорошая батарея, и вообще неплохой смартфон'); ?>
                        </div>
                        <div>
                            <span class="disadvantages"><?php echo __('Disadvantages'); ?>:</span>
                            <?php echo __('не обнаружены'); ?>
                        </div>
                    </div>
                    <div class="review-additional">
                        <div class="replies">
                            <a href="#">1 <?php echo __('reply(ies)') ?></a>
                            <a href="#"><?php echo __('Reply') ?></a>
                        </div>
                        <div class="likes">
                            <span><?php echo __('Was this review helpful to you'); ?>:</span>
                            <a href="#" class="like">14</a>
                            <a href="#" class="dislike">3</a>
                        </div>
                    </div>
                </div>

            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif;?>
