<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="review-form-block">
    <button type="button" title="review form trigger" id="review-form-trigger" class="action secondary">
         <span><?php /* @escapeNotVerified */ echo __('Send Review'); ?></span>
    </button>
</div>
<div id="product-review-container" data-role="product-review"></div>
<?php echo $block->getChildHtml(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews-theme": {
                "productReviewUrl": "<?php /* @escapeNotVerified */ echo $block->getProductReviewUrl();?>",
                "reviewClosedHeight": 60,
                "reviewOpenLabel": "<?php /* @escapeNotVerified */ echo __('Read more'); ?>",
                "reviewCloseLabel": "<?php /* @escapeNotVerified */ echo __('Hide'); ?>",
                "allClosedHeight": 766,
                "allOpenLabel": "<?php /* @escapeNotVerified */ echo __('Show all reviews'); ?>",
                "allCloseLabel": "<?php /* @escapeNotVerified */ echo __('Hide'); ?>"
            }
        }
    }
</script>
