<?php
/**
 * Copyright © 2013-2017 ImproDev, Inc. All rights reserved.
 *
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions options switcher-options">
        <ul class="switcher-dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php $notCurrentLang = $_lang->getId() != $block->getCurrentStoreId(); ?>
                <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option <?php echo $notCurrentLang ? '' : 'active' ?>">
                    <?php if($notCurrentLang): ?>
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                    <?php endif; ?>
                        <span><?php echo __($block->escapeHtml($_lang->getName())); ?></span>
                    <?php if($notCurrentLang): ?>
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
