<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$isServiceModule = false;
if(class_exists('ImproDev\ServiceModule\Helper\Data')) {
    $productHelper = $this->helper('ImproDev\ServiceModule\Helper\Data');
    $isServiceModule = true;
}

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $detailedInfoGroup = $isServiceModule ? $productHelper->resortInfoGroup($detailedInfoGroup) : $detailedInfoGroup; ?>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    $closedHeight = $alias == 'additional' ? 360 : 180;
                    $openLabel = $alias == 'additional' ? __('Show all') . ' ' . __($label) : __('Read more');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo __($label); ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content"
                    data-mage-init='{"showMoreLess":{
                                        "openLabel": "<?php echo $openLabel; ?>",
                                        "closeLabel": "<?php echo __('Hide'); ?>",
                                        "closedHeight": "<?php echo $closedHeight; ?>"
                                    }}'>
                    <span class="tab-label">
                        <?php /* @escapeNotVerified */ echo __($label) . ' ' . __('by product'); ?>
                    </span>
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
