<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare" title="<?php /* @escapeNotVerified */ echo __("Compare Products"); ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': false}"
    ><?php /* @escapeNotVerified */ echo __("Compare Products"); ?><!-- ko if: compareProducts().count --><span class="counter qty" data-bind="text: parseInt(compareProducts().countCaption)"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
